language: python
python:
  - "2.7"
if: tag IS present
addons:
  apt:
    packages:
      - ansible
before_install:
  - openssl aes-256-cbc -K $encrypted_465f01a5e248_key -iv $encrypted_465f01a5e248_iv -in creds.json.enc -out creds.json -d
install:
  - pip install apache-libcloud
script:
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - ansible build/playbook.yaml
